import Navbar from "@/components/Header";
import "./globals.css";
import ToastProvider from "@/components/ToastProvider";

export const metadata = {
  title: "SkillSwap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
         <ToastProvider />
      </body>
    </html>
  );
}
